lock_manager:
  zwave_node_id: 3
  tags:
    - name: Tom
      user_code: !secret user_code_tom
      index: 1
    - name: Alice
      user_code: !secret user_code_alice
      index: 2
    - name: Bob
      user_code: !secret user_code_bob
      index: 3
    - name: Kreacher
      user_code: !secret user_code_kreacher
      index: 4
